site_name: Credit Card Default Prediction
nav:
  - Home: index.md

theme:
  name: material

pages:
  - Home: index.md
  - Other Page: other.md

markdown_extensions:
  - pymdownx.highlight

extra_javascript:
  - javascripts/mathjax.js

plugins:
  - search

index: index.md
