site_name: Credit Card Default Prediction
nav:
  - Home: index.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime    


markdown_extensions:
  - pymdownx.highlight

extra_javascript:
  - javascripts/mathjax.js

plugins:
  - search

